from config.database import db

class vw_obyekbadan(db.Model):
    __tablename__ = 'vw_obyekpajak'  # Nama tabel asli

    OPDID = db.Column(db.Integer, primary_key=True)
    NamaOPD = db.Column(db.String)
    UsahaBadan = db.Column(db.Integer)
    WPID = db.Column(db.Integer)
    WapuID = db.Column(db.Integer)
    WajibPungut = db.Column(db.String, nullable=False)
    TglPendaftaran = db.Column(db.DateTime, nullable=False)
    TglPendataan = db.Column(db.DateTime)
    KecamatanOPD = db.Column(db.Integer)
    KelurahanOPD = db.Column(db.Integer)
    AlamatOPD = db.Column(db.String)
    vw_al_usaha = db.Column(db.String, nullable=True)
    RWOPD = db.Column(db.Integer)
    RTOPD = db.Column(db.Integer)
    NoTelpOPD = db.Column(db.String)
    JenisPendapatanID = db.Column(db.String, nullable=True)
    KodeRekening = db.Column(db.String, nullable=True)
    NamaJenisPendapatan = db.Column(db.String, nullable=False)
    SelfAssesment = db.Column(db.Boolean)
    GrupUsahaID = db.Column(db.Integer)
    LokasiID = db.Column(db.String, nullable=False)
    NamaLokasi = db.Column(db.String, nullable=False)
    KlasifikasiID = db.Column(db.Integer)
    Insidentil = db.Column(db.String, nullable=False)
    NamaPengelola = db.Column(db.String)
    AlamatPengelola = db.Column(db.String)
    KotaPengelola = db.Column(db.String)
    KecamatanPengelola = db.Column(db.String)
    KelurahanPengelola = db.Column(db.String)
    RWPengelola = db.Column(db.Integer)
    RTPengelola = db.Column(db.Integer)
    NoTelpPengelola = db.Column(db.String)
    NPWPPengelola = db.Column(db.String)
    NPWPUsaha = db.Column(db.String)
    DateUpd = db.Column(db.DateTime)
    avatar = db.Column(db.String)
    latlng = db.Column(db.String)
    NOP = db.Column(db.String)
    TglNOP = db.Column(db.DateTime)
    klas = db.Column(db.String, nullable=True)
    TglPenghapusan = db.Column(db.TIMESTAMP, nullable=True, default=None)

    # Relasi dengan MsJenisPendapatan
    jenis_pendapatan = db.relationship("MsJenisPendapatan", foreign_keys=[UsahaBadan], primaryjoin="vw_obyekbadan.UsahaBadan == MsJenisPendapatan.JenisPendapatanID", lazy='joined')

    # Relasi dengan MsWapu
    wajib_pungut = db.relationship("MsWapu", foreign_keys=[WapuID], primaryjoin="vw_obyekbadan.WapuID == MsWapu.WapuID", lazy='joined')